### ISSUE TITLE
Add Zone hooks documentation 

### ISSUE THREAD

**Issue by alephcero** [urbansim/urbansim_hooks#40]
Documentation in Zone hooks, both `.rst` file and rendered `html`.

**Comment by alephcero** [comment]
Zone Docs should include a `variables.py` [modification](https://urbansim.github.io/urbansim_hooks/parcel-hooks.html#configure-variables-py) like parcels?

**Comment by PyMap** [comment]
Modifications in variables.py will be tested when scenarios can be created with skims. At the moment, that file is not modified. Now I am having the following error(`SyntaxError: name 'vacant_unit' is used prior to global declaration`) with sphinx because of the declaration of a global variable. When I can create scenarios with adjustments I should try the code and solve this [syntax error](https://aroberge.github.io/friendly-traceback-docs/docs/html/syntax_tracebacks_en_3.8.html#syntaxerror-used-prior-to-global-declaration)
